In [2]:

import gurobipy as gp
from gurobipy import GRB
import numpy as np


In [3]:
A = np.array([[0, -1, 1], \
              [1, 0, -1], \
              [-1, 1, 0]]) # this is the payoff matrix of rps
num_actions = A.shape[0]
e = np.ones(num_actions)
x = np.ones(num_actions)
v = 0

In [4]:
v * e

array([0., 0., 0.])

In [5]:
A.dot(x) - v*e

array([0., 0., 0.])

In [7]:
A >= -A.T

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [7]:
e.dot(x)

3.0